apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "krakend.fullname" . }}-configmap{{ if .Values.isAppendVersion }}-{{ regexReplaceAll "\\W+" .Chart.Version "-" }} {{ end }}
data:
  krakend.json: |-
{{- if .Values.krakendJson }}
{{ .Values.krakendJson | indent 4 }}
{{- else }}
{{ .Files.Get "config/krakend.json" | indent 4 }}
{{- end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "krakend.fullname" . }}-settings-configmap{{ if .Values.isAppendVersion }}-{{ regexReplaceAll "\\W+" .Chart.Version "-" }} {{ end }}
data:
  url.json: |-
{{- if empty .Values.backendUrl }}
{{ .Files.Get "config/settings/url.json" | indent 4 }}
{{- else }}
{{ toJson .Values.backendUrl | indent 4 }}
{{- end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "krakend.fullname" . }}-templates-configmap{{ if .Values.isAppendVersion }}-{{ regexReplaceAll "\\W+" .Chart.Version "-" }} {{ end }}
data:
  endpoints.tmpl: |-
{{- $index := 0 }}
{{- range $path, $_ := .Files.Glob  "config/templates/**.tmpl" }}
{{- if $index }}
{{ printf "%s" "," | indent 4 }}
{{- end }}
{{ $.Files.Get $path | indent 4 }}
{{- $index = add1 $index }}
{{- end }}
{{- if .Values.extraEndpoints }}
{{- printf "," }}
{{ tpl .Values.extraEndpoints . | indent 4 }}
{{- end }}
  extraConfig.tmpl: |-
    {
      "middlewares": {
        "krakend-jwt-validation": {
          "vault_url": "{{ .Values.vault.url }}",
          "vault_role_name": "{{ .Values.vault.roleName }}"
        }
      }{{- if .Values.extraConfig }}{{ printf "," }}
  {{ tpl .Values.extraConfig . | indent 4 }}{{- end }}
    }
